import {ThemeDefinition} from '@app-types/theme.types';
import {LogoPixelBlue} from '@assets/images';

/** Theme 2: Pixel Blue — retro 8-bit, sharp/blocky radii, blue-tinted shadows. */
export const pixelBlue: ThemeDefinition = {
  id: 'pixel-blue',
  name: 'Pixel Blue',
  description: 'Retro gaming, playful',
  mascotImage: LogoPixelBlue,
  isDark: false,
  colors: {
    background: '#E8F0FE',
    surface: '#D4E4FC',
    surfaceVariant: '#C4D8F5',
    card: '#F5F9FF',
    primary: '#1A3A5C',
    primaryLight: '#2C5480',
    primaryDark: '#102438',
    onPrimary: '#FFFFFF',
    accent: '#4A90D9',
    accentLight: '#6FA9E6',
    onAccent: '#FFFFFF',
    textPrimary: '#1A3A5C',
    textSecondary: '#4A6FA5',
    textTertiary: '#8AA4C4',
    textInverse: '#FFFFFF',
    border: '#B8D4F0',
    divider: '#C4DAF2',
    success: '#2E9E5B',
    warning: '#E6A100',
    error: '#D64545',
    info: '#4A90D9',
    silentMode: '#4A90D9',
    vibrateMode: '#E6A100',
    normalMode: '#2E9E5B',
    mapZoneCircle: 'rgba(74, 144, 217, 0.18)',
    mapZoneStroke: '#4A90D9',
    overlay: 'rgba(16, 36, 56, 0.55)',
    skeleton: '#C4D8F5',
    ripple: 'rgba(26, 58, 92, 0.12)',
  },
  typography: {
    fontFamily: {
      regular: 'JetBrainsMono-Regular',
      medium: 'JetBrainsMono-Medium',
      semibold: 'JetBrainsMono-Bold',
      bold: 'JetBrainsMono-Bold',
    },
    sizes: {
      xs: 10,
      sm: 12,
      base: 14,
      md: 16,
      lg: 18,
      xl: 20,
      '2xl': 24,
      '3xl': 30,
      '4xl': 36,
    },
    lineHeights: {tight: 1.2, normal: 1.5, relaxed: 1.75},
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    base: 16,
    lg: 20,
    xl: 24,
    '2xl': 32,
    '3xl': 40,
    '4xl': 48,
  },
  borderRadius: {none: 0, sm: 2, md: 3, lg: 4, xl: 6, '2xl': 6, full: 9999},
  shadows: {
    sm: {
      shadowColor: '#1A3A5C',
      shadowOffset: {width: 2, height: 2},
      shadowOpacity: 0.15,
      shadowRadius: 0,
      elevation: 2,
    },
    md: {
      shadowColor: '#1A3A5C',
      shadowOffset: {width: 3, height: 3},
      shadowOpacity: 0.2,
      shadowRadius: 0,
      elevation: 4,
    },
    lg: {
      shadowColor: '#1A3A5C',
      shadowOffset: {width: 4, height: 4},
      shadowOpacity: 0.25,
      shadowRadius: 0,
      elevation: 6,
    },
  },
  componentDefaults: {
    buttonBorderRadius: 3,
    cardBorderRadius: 4,
    inputBorderRadius: 3,
    iconSize: 24,
    avatarSize: 40,
  },
};
