import {ThemeDefinition} from '@app-types/theme.types';
import {LogoSoftLavender} from '@assets/images';

/** Theme 3: Soft Lavender — warm, pillowy, very rounded, soft purple shadows. */
export const softLavender: ThemeDefinition = {
  id: 'soft-lavender',
  name: 'Soft Lavender',
  description: 'Warm and soothing',
  mascotImage: LogoSoftLavender,
  isDark: false,
  colors: {
    background: '#F5F0FF',
    surface: '#EDE5FF',
    surfaceVariant: '#E3D8FA',
    card: '#FBF8FF',
    primary: '#7C4DFF',
    primaryLight: '#9B75FF',
    primaryDark: '#5E35D9',
    onPrimary: '#FFFFFF',
    accent: '#00BCD4',
    accentLight: '#4DD0E1',
    onAccent: '#FFFFFF',
    textPrimary: '#3D2C6E',
    textSecondary: '#7E6BAD',
    textTertiary: '#AC9ED1',
    textInverse: '#FFFFFF',
    border: '#D4C5F0',
    divider: '#DFD3F5',
    success: '#00C48C',
    warning: '#FFB25E',
    error: '#FF6B8A',
    info: '#00BCD4',
    silentMode: '#7C4DFF',
    vibrateMode: '#FFB25E',
    normalMode: '#00C48C',
    mapZoneCircle: 'rgba(124, 77, 255, 0.15)',
    mapZoneStroke: '#7C4DFF',
    overlay: 'rgba(61, 44, 110, 0.45)',
    skeleton: '#E3D8FA',
    ripple: 'rgba(124, 77, 255, 0.12)',
  },
  typography: {
    fontFamily: {
      regular: 'Quicksand-Regular',
      medium: 'Quicksand-Medium',
      semibold: 'Quicksand-SemiBold',
      bold: 'Quicksand-Bold',
    },
    sizes: {
      xs: 10,
      sm: 12,
      base: 14,
      md: 16,
      lg: 18,
      xl: 20,
      '2xl': 24,
      '3xl': 30,
      '4xl': 36,
    },
    lineHeights: {tight: 1.25, normal: 1.6, relaxed: 1.8},
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    base: 16,
    lg: 20,
    xl: 24,
    '2xl': 32,
    '3xl': 40,
    '4xl': 48,
  },
  borderRadius: {
    none: 0,
    sm: 8,
    md: 16,
    lg: 20,
    xl: 24,
    '2xl': 28,
    full: 9999,
  },
  shadows: {
    sm: {
      shadowColor: '#7C4DFF',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.12,
      shadowRadius: 6,
      elevation: 2,
    },
    md: {
      shadowColor: '#7C4DFF',
      shadowOffset: {width: 0, height: 4},
      shadowOpacity: 0.16,
      shadowRadius: 12,
      elevation: 4,
    },
    lg: {
      shadowColor: '#7C4DFF',
      shadowOffset: {width: 0, height: 8},
      shadowOpacity: 0.2,
      shadowRadius: 20,
      elevation: 8,
    },
  },
  componentDefaults: {
    buttonBorderRadius: 20,
    cardBorderRadius: 24,
    inputBorderRadius: 16,
    iconSize: 24,
    avatarSize: 44,
  },
};
