import {ThemeDefinition} from '@app-types/theme.types';
import {LogoHoloDark} from '@assets/images';

/** Theme 4: Holo Dark — futuristic, iridescent, glowing purple neon shadows. */
export const holoDark: ThemeDefinition = {
  id: 'holo-dark',
  name: 'Holo Dark',
  description: 'Futuristic and premium',
  mascotImage: LogoHoloDark,
  isDark: true,
  colors: {
    background: '#0A0A1A',
    surface: '#141428',
    surfaceVariant: '#1C1C38',
    card: '#141428',
    primary: '#8B5CF6',
    primaryLight: '#A78BFA',
    primaryDark: '#6D28D9',
    onPrimary: '#FFFFFF',
    accent: '#06B6D4',
    accentLight: '#22D3EE',
    onAccent: '#04121A',
    textPrimary: '#E8E0F0',
    textSecondary: '#A09AB8',
    textTertiary: '#6B6688',
    textInverse: '#0A0A1A',
    border: '#2D2D50',
    divider: '#242444',
    success: '#22C55E',
    warning: '#FBBF24',
    error: '#F43F5E',
    info: '#06B6D4',
    silentMode: '#8B5CF6',
    vibrateMode: '#FBBF24',
    normalMode: '#22C55E',
    mapZoneCircle: 'rgba(139, 92, 246, 0.22)',
    mapZoneStroke: '#8B5CF6',
    overlay: 'rgba(0, 0, 0, 0.65)',
    skeleton: '#1C1C38',
    ripple: 'rgba(139, 92, 246, 0.2)',
  },
  typography: {
    fontFamily: {
      regular: 'Inter-Regular',
      medium: 'Inter-Medium',
      semibold: 'Inter-SemiBold',
      bold: 'Inter-Bold',
    },
    sizes: {
      xs: 10,
      sm: 12,
      base: 14,
      md: 16,
      lg: 18,
      xl: 20,
      '2xl': 24,
      '3xl': 30,
      '4xl': 36,
    },
    lineHeights: {tight: 1.2, normal: 1.5, relaxed: 1.75},
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    base: 16,
    lg: 20,
    xl: 24,
    '2xl': 32,
    '3xl': 40,
    '4xl': 48,
  },
  borderRadius: {
    none: 0,
    sm: 6,
    md: 10,
    lg: 14,
    xl: 18,
    '2xl': 24,
    full: 9999,
  },
  shadows: {
    sm: {
      shadowColor: '#8B5CF6',
      shadowOffset: {width: 0, height: 0},
      shadowOpacity: 0.3,
      shadowRadius: 6,
      elevation: 3,
    },
    md: {
      shadowColor: '#8B5CF6',
      shadowOffset: {width: 0, height: 0},
      shadowOpacity: 0.35,
      shadowRadius: 12,
      elevation: 6,
    },
    lg: {
      shadowColor: '#8B5CF6',
      shadowOffset: {width: 0, height: 0},
      shadowOpacity: 0.4,
      shadowRadius: 24,
      elevation: 10,
    },
  },
  componentDefaults: {
    buttonBorderRadius: 12,
    cardBorderRadius: 14,
    inputBorderRadius: 10,
    iconSize: 24,
    avatarSize: 40,
  },
};
