import {ThemeDefinition} from '@app-types/theme.types';
import {LogoMinimalLight} from '@assets/images';

export const minimalLight: ThemeDefinition = {
  id: 'minimal-light',
  name: 'Minimal Light',
  description: 'Clean and professional',
  mascotImage: LogoMinimalLight,
  isDark: false,
  colors: {
    background: '#FFFFFF',
    surface: '#F8F9FA',
    surfaceVariant: '#F0F1F3',
    card: '#FFFFFF',
    primary: '#1A1A2E',
    primaryLight: '#16213E',
    primaryDark: '#0F0F1A',
    onPrimary: '#FFFFFF',
    accent: '#E94560',
    accentLight: '#FF6B6B',
    onAccent: '#FFFFFF',
    textPrimary: '#1A1A2E',
    textSecondary: '#6C757D',
    textTertiary: '#ADB5BD',
    textInverse: '#FFFFFF',
    border: '#E9ECEF',
    divider: '#DEE2E6',
    success: '#28A745',
    warning: '#FFC107',
    error: '#DC3545',
    info: '#17A2B8',
    silentMode: '#6C63FF',
    vibrateMode: '#FF9F43',
    normalMode: '#2ED573',
    mapZoneCircle: 'rgba(108, 99, 255, 0.15)',
    mapZoneStroke: '#6C63FF',
    overlay: 'rgba(0, 0, 0, 0.5)',
    skeleton: '#E9ECEF',
    ripple: 'rgba(26, 26, 46, 0.1)',
  },
  typography: {
    fontFamily: {
      regular: 'Inter-Regular',
      medium: 'Inter-Medium',
      semibold: 'Inter-SemiBold',
      bold: 'Inter-Bold',
    },
    sizes: {
      xs: 10,
      sm: 12,
      base: 14,
      md: 16,
      lg: 18,
      xl: 20,
      '2xl': 24,
      '3xl': 30,
      '4xl': 36,
    },
    lineHeights: {tight: 1.2, normal: 1.5, relaxed: 1.75},
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    base: 16,
    lg: 20,
    xl: 24,
    '2xl': 32,
    '3xl': 40,
    '4xl': 48,
  },
  borderRadius: {none: 0, sm: 4, md: 8, lg: 12, xl: 16, '2xl': 20, full: 9999},
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 1},
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 3,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 4},
      shadowOpacity: 0.12,
      shadowRadius: 8,
      elevation: 6,
    },
  },
  componentDefaults: {
    buttonBorderRadius: 8,
    cardBorderRadius: 12,
    inputBorderRadius: 8,
    iconSize: 24,
    avatarSize: 40,
  },
};
