export const SCREENS = {
  // Auth
  Onboarding: 'Onboarding',
  Login: 'Login',
  Signup: 'Signup',
  ForgotPassword: 'ForgotPassword',
  // Home
  HomeScreen: 'HomeScreen',
  AddEditZone: 'AddEditZone',
  ZoneDetails: 'ZoneDetails',
  // Sharing
  LocationSharing: 'LocationSharing',
  LiveShareView: 'LiveShareView',
  // Profiles
  Profiles: 'Profiles',
  AddEditProfile: 'AddEditProfile',
  // Settings
  Settings: 'Settings',
  AppearanceSettings: 'AppearanceSettings',
  NotificationSettings: 'NotificationSettings',
  LocationSettings: 'LocationSettings',
  DataSettings: 'DataSettings',
  Account: 'Account',
  Subscription: 'Subscription',
  About: 'About',
  HelpSupport: 'HelpSupport',
  // Tabs
  HomeTab: 'HomeTab',
  SharingTab: 'SharingTab',
  ProfileTab: 'ProfileTab',
  SettingsTab: 'SettingsTab',
} as const;
